package com.example.fishstock.agents;

import com.example.fishstock.eval.Category;
import com.example.fishstock.eval.EvalWeights;

import java.io.Serializable;
import java.util.EnumMap;
import java.util.Locale;
import java.util.Map;

/**
 * A recipe for an agent: what kind it is, its weights and how long it thinks.
 * Small and serializable, so it can be passed between screens, saved, or generated by a
 * training run. {@link AgentFactory} turns a spec into a playing {@link Agent}.
 */
public final class AgentSpec implements Serializable {
  public enum Kind { HUMAN, RANDY, SIMPLE, MINMAX, FISHSTOCK, CUSTOM }

  public final Kind kind;
  public final String name;
  /** Only used by CUSTOM agents. Per-category slider values (1.0 = default). */
  public final Map<Category, Double> sliders;
  /** CUSTOM only: 0 = look one move ahead (like Simple), otherwise MinMax for this long. */
  public final long thinkTimeMs;

  private AgentSpec(Kind kind, String name, Map<Category, Double> sliders, long thinkTimeMs) {
    this.kind = kind;
    this.name = name;
    this.sliders = sliders;
    this.thinkTimeMs = thinkTimeMs;
  }

  public static AgentSpec builtIn(Kind kind) {
    String name = kind.name().charAt(0) + kind.name().substring(1).toLowerCase(Locale.US);
    if (kind == Kind.MINMAX) name = "MinMax";
    if (kind == Kind.FISHSTOCK) name = "FishStock";
    return new AgentSpec(kind, name, EvalWeights.neutralFactors(), 0);
  }

  public static AgentSpec custom(String name, Map<Category, Double> sliders, long thinkTimeMs) {
    Map<Category, Double> copy = new EnumMap<>(Category.class);
    copy.putAll(EvalWeights.neutralFactors());
    copy.putAll(sliders);
    return new AgentSpec(Kind.CUSTOM, name, copy, thinkTimeMs);
  }

  /** Looks up a built-in agent by the names used on the main screen ("Randy", "MinMax", ...). */
  public static AgentSpec byName(String name) {
    if (name == null) return builtIn(Kind.HUMAN);
    for (Kind k : Kind.values()) {
      if (k != Kind.CUSTOM && k.name().equalsIgnoreCase(name)) return builtIn(k);
    }
    return builtIn(Kind.HUMAN);
  }

  /** The weights a custom agent plays with: the defaults, scaled by its sliders. */
  public EvalWeights weights() {
    return EvalWeights.defaults().scaledBy(sliders);
  }

  /** One line of text: "kind|name|thinkMs|CATEGORY=1.0,CATEGORY=0.5,..." */
  public String serialize() {
    StringBuilder sb = new StringBuilder();
    sb.append(kind.name()).append('|').append(name.replace("|", " ")).append('|').append(thinkTimeMs).append('|');
    boolean first = true;
    for (Map.Entry<Category, Double> e : sliders.entrySet()) {
      if (!first) sb.append(',');
      first = false;
      sb.append(e.getKey().name()).append('=').append(String.format(Locale.US, "%.2f", e.getValue()));
    }
    return sb.toString();
  }

  public static AgentSpec parse(String line) {
    String[] parts = line.split("\\|", -1);
    Kind kind = Kind.valueOf(parts[0]);
    if (kind != Kind.CUSTOM) return builtIn(kind);
    Map<Category, Double> sliders = new EnumMap<>(Category.class);
    if (parts.length > 3 && !parts[3].isEmpty()) {
      for (String kv : parts[3].split(",")) {
        String[] p = kv.split("=");
        try {
          sliders.put(Category.valueOf(p[0]), Double.parseDouble(p[1]));
        } catch (RuntimeException ignored) {
          // category renamed since saving: keep default
        }
      }
    }
    return custom(parts[1], sliders, Long.parseLong(parts[2]));
  }
}
