package com.example.fishstock.agents;

import com.example.fishstock.eval.Category;
import com.example.fishstock.eval.EvalWeights;

import java.io.Serializable;
import java.util.EnumMap;
import java.util.Locale;
import java.util.Map;

/**
 * A recipe for an agent: what kind it is, its weights and how long it thinks.
 * Small and serializable, so it can be passed between screens, saved, or generated by a
 * training run. {@link AgentFactory} turns a spec into a playing {@link Agent}.
 */
public final class AgentSpec implements Serializable {
  public enum Kind { HUMAN, BLUNDER, RANDY, SIMPLE, LAZY, MINMAX, LAZY_PLUS, MINMAX_PLUS, AGRO, TIMID, FISHSTOCK, CUSTOM }

  public final Kind kind;
  public final String name;
  /** Only used by CUSTOM agents. Per-category slider values (1.0 = default). */
  public final Map<Category, Double> sliders;
  /** CUSTOM only: 0 = look one move ahead (like Simple), otherwise MinMax for this long. */
  public final long thinkTimeMs;
  /** -1 (Timid) .. 0 (neutral) .. +1 (Agro). See {@link PlayStyle}. */
  public final double aggression;

  private AgentSpec(Kind kind, String name, Map<Category, Double> sliders, long thinkTimeMs, double aggression) {
    this.kind = kind;
    this.name = name;
    this.sliders = sliders;
    this.thinkTimeMs = thinkTimeMs;
    this.aggression = Math.max(-1, Math.min(1, aggression));
  }

  public static AgentSpec builtIn(Kind kind) {
    String name = kind.name().charAt(0) + kind.name().substring(1).toLowerCase(Locale.US);
    if (kind == Kind.MINMAX) name = "MinMax";
    if (kind == Kind.FISHSTOCK) name = "FishStock";
    if (kind == Kind.LAZY_PLUS) name = "Lazy+";
    if (kind == Kind.MINMAX_PLUS) name = "MinMax+";
    Map<Category, Double> sliders = new EnumMap<>(Category.class);
    sliders.putAll(EvalWeights.neutralFactors());
    double aggression = 0;
    if (kind == Kind.AGRO) {
      sliders.putAll(PlayStyle.agroSliders());
      aggression = 1;
    } else if (kind == Kind.TIMID) {
      sliders.putAll(PlayStyle.timidSliders());
      aggression = -1;
    }
    return new AgentSpec(kind, name, sliders, 0, aggression);
  }

  public static AgentSpec custom(String name, Map<Category, Double> sliders, long thinkTimeMs) {
    return custom(name, sliders, thinkTimeMs, 0);
  }

  public static AgentSpec custom(String name, Map<Category, Double> sliders, long thinkTimeMs, double aggression) {
    Map<Category, Double> copy = new EnumMap<>(Category.class);
    copy.putAll(EvalWeights.neutralFactors());
    copy.putAll(sliders);
    return new AgentSpec(Kind.CUSTOM, name, copy, thinkTimeMs, aggression);
  }

  /** The computer opponents in level order (-1 to 3). */
  public static final Kind[] LEVELS = {Kind.BLUNDER, Kind.RANDY, Kind.SIMPLE, Kind.MINMAX, Kind.FISHSTOCK};

  /**
   * The home screen's opponents, in level order: Simple (material only) -> Lazy (the full original
   * evaluation, one move ahead) -> MinMax (original evaluation, searching) -> Agro and Timid
   * (improved evaluation) -> FishStock (improved evaluation with self-play-tuned weights).
   */
  public static final Kind[] OPPONENTS = {
      Kind.BLUNDER, Kind.RANDY, Kind.SIMPLE, Kind.LAZY, Kind.MINMAX, Kind.AGRO, Kind.TIMID, Kind.FISHSTOCK};

  /**
   * The Tournament screen also has Lazy+ and MinMax+: Lazy and MinMax with the improved evaluation,
   * for measuring what the new evaluation is worth (and the baseline the tuning started from).
   */
  public static final Kind[] TOURNAMENT_AGENTS = {
      Kind.BLUNDER, Kind.RANDY, Kind.SIMPLE, Kind.LAZY, Kind.LAZY_PLUS, Kind.MINMAX, Kind.MINMAX_PLUS,
      Kind.AGRO, Kind.TIMID, Kind.FISHSTOCK};

  /** Level shown on the home screen (-1 = Blunder ... 5 = FishStock); custom agents have none. */
  public int level() {
    for (int i = 0; i < OPPONENTS.length; i++) if (OPPONENTS[i] == kind) return i - 1;
    return Integer.MIN_VALUE;
  }

  /** One line about how this opponent plays. */
  public String description() {
    switch (kind) {
      case BLUNDER: return "Plays the move it likes least. Hard to lose to.";
      case RANDY: return "Plays a random legal move.";
      case SIMPLE: return "Counts material and won't leave a piece hanging. Knows nothing else.";
      case LAZY: return "Looks one move ahead with the full original evaluation.";
      case LAZY_PLUS: return "Lazy with the improved evaluation (threats, king danger, bad pieces...).";
      case MINMAX_PLUS: return "MinMax with the improved evaluation, untuned (FishStock's starting point).";
      case TIMID: return "Takes its time (about 6 s a move). Hates to capture, guards its king and pawns. Fianchettoes.";
      case AGRO: return "Thinks fast (about 2 s a move). Grabs pieces, gives checks, hunts for mates. Plays gambits.";
      case MINMAX: return "Searches several moves ahead (about 5 s a move) with the original evaluation.";
      case FISHSTOCK: return "The final boss: improved evaluation tuned by thousands of self-play games, 7 s a move.";
      case CUSTOM: return String.format(Locale.US, "Your agent. %s, aggression %+d%%. Opens: %s.",
          thinkTimeMs <= 0 ? "Looks one move ahead" : String.format(Locale.US, "Thinks %.1f s a move", thinkTimeMs / 1000.0),
          Math.round(aggression * 100), OpeningBook.repertoireFor(aggression).label);
      default: return "";
    }
  }

  /** Names a custom agent may not use, because a built-in agent already has them. */
  public static boolean isBuiltInName(String name) {
    for (Kind k : Kind.values()) {
      if (k != Kind.CUSTOM && builtIn(k).name.equalsIgnoreCase(name)) return true;
    }
    return false;
  }

  /** Looks up a built-in agent by the names used on the main screen ("Randy", "MinMax", ...). */
  public static AgentSpec byName(String name) {
    if (name == null) return builtIn(Kind.HUMAN);
    for (Kind k : Kind.values()) {
      if (k == Kind.CUSTOM) continue;
      if (k.name().equalsIgnoreCase(name) || builtIn(k).name.equalsIgnoreCase(name)) return builtIn(k);
    }
    return builtIn(Kind.HUMAN);
  }

  /** The weights a custom agent (or Agro / Timid) plays with: the defaults, scaled by its sliders. */
  public EvalWeights weights() {
    return EvalWeights.defaults().scaledBy(sliders);
  }

  /** How it chooses between moves (captures, checks, own vs enemy weaknesses). */
  public PlayStyle style() {
    return PlayStyle.fromAggression(aggression);
  }

  /** One line of text: "kind|name|thinkMs|CATEGORY=1.0,CATEGORY=0.5,...|aggression" */
  public String serialize() {
    StringBuilder sb = new StringBuilder();
    sb.append(kind.name()).append('|').append(name.replace("|", " ")).append('|').append(thinkTimeMs).append('|');
    boolean first = true;
    for (Map.Entry<Category, Double> e : sliders.entrySet()) {
      if (!first) sb.append(',');
      first = false;
      sb.append(e.getKey().name()).append('=').append(String.format(Locale.US, "%.2f", e.getValue()));
    }
    sb.append('|').append(String.format(Locale.US, "%.2f", aggression));
    return sb.toString();
  }

  public static AgentSpec parse(String line) {
    String[] parts = line.split("\\|", -1);
    Kind kind = Kind.valueOf(parts[0]);
    if (kind != Kind.CUSTOM) return builtIn(kind);
    Map<Category, Double> sliders = new EnumMap<>(Category.class);
    if (parts.length > 3 && !parts[3].isEmpty()) {
      for (String kv : parts[3].split(",")) {
        String[] p = kv.split("=");
        try {
          sliders.put(Category.valueOf(p[0]), Double.parseDouble(p[1]));
        } catch (RuntimeException ignored) {
          // category renamed since saving: keep default
        }
      }
    }
    double aggression = 0;
    if (parts.length > 4 && !parts[4].isEmpty()) {
      try {
        aggression = Double.parseDouble(parts[4]);
      } catch (NumberFormatException ignored) {
        // saved by an older version: neutral
      }
    }
    return custom(parts[1], sliders, Long.parseLong(parts[2]), aggression);
  }
}
